export interface Property {
  id: string
  title: string
  description?: string
  location: string
  price: number
  priceType?: "perNight" | "monthly" | "yearly" | "sale"
  bedrooms?: number
  bathrooms?: number
  squareFeet?: number
  landSize?: number
  landUnit?: string
  images: string[]
  featured?: boolean
  propertyType?: string
  amenities?: string[]
  isLandedProperty?: boolean
  rating?: number
  reviews?: number
  dates?: string
  favorite?: boolean
  type?: string
  beds?: number
  baths?: number
  maxGuests?: number
  categories?: string[]
  yearBuilt?: number
  newListing?: boolean
}

export const sampleProperties: Property[] = [
  {
    id: "1",
    title: "Luxury Ocean View Apartment",
    description: "Stunning apartment with panoramic ocean views, modern amenities, and prime location.",
    location: "Victoria Island, Lagos",
    price: 250000,
    priceType: "monthly",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    images: ["/luxury-ocean-view-apartment.png"],
    featured: true,
    propertyType: "apartment",
    amenities: ["Swimming Pool", "Gym", "24/7 Security", "Parking"],
    rating: 4.9,
    reviews: 124,
    dates: "Available all year",
    favorite: false,
    type: "Apartment",
    beds: 3,
    baths: 2,
    maxGuests: 6,
    categories: ["apartments", "luxury", "beachfront"],
    yearBuilt: 2020,
    newListing: true,
  },
  {
    id: "2",
    title: "Modern Lekki Apartment",
    description: "Contemporary apartment in the heart of Lekki with high-end finishes and amenities.",
    location: "Lekki Phase 1, Lagos",
    price: 180000,
    priceType: "monthly",
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    images: ["/lekki-apartment.png"],
    featured: false,
    propertyType: "apartment",
    amenities: ["Swimming Pool", "Gym", "Parking"],
    rating: 4.7,
    reviews: 86,
    dates: "Available all year",
    favorite: false,
    type: "Apartment",
    beds: 2,
    baths: 2,
    maxGuests: 4,
    categories: ["apartments", "shortlets"],
  },
  {
    id: "3",
    title: "Elegant Villa with Pool",
    description: "Spacious villa with private pool, garden, and luxury finishes throughout.",
    location: "Ikoyi, Lagos",
    price: 450000,
    priceType: "monthly",
    bedrooms: 5,
    bathrooms: 5,
    squareFeet: 4500,
    images: ["/elegant-villa-lagos.png"],
    featured: true,
    propertyType: "villa",
    amenities: ["Private Pool", "Garden", "Security", "Parking"],
    rating: 4.8,
    reviews: 92,
    dates: "Available all year",
    favorite: false,
    type: "Villa",
    beds: 5,
    baths: 4,
    maxGuests: 10,
    categories: ["villas", "luxury"],
    yearBuilt: 2019,
  },
  {
    id: "4",
    title: "Modern Ikoyi Apartment",
    description: "Sleek, modern apartment with high ceilings and premium finishes.",
    location: "Ikoyi, Lagos",
    price: 220000,
    priceType: "monthly",
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 1600,
    images: ["/modern-ikoyi-apartment.png"],
    featured: false,
    propertyType: "apartment",
    amenities: ["Gym", "24/7 Security", "Parking"],
    rating: 4.7,
    reviews: 78,
    dates: "Available all year",
    favorite: false,
    type: "Apartment",
    beds: 3,
    baths: 3,
    maxGuests: 6,
    categories: ["apartments", "luxury"],
  },
  {
    id: "5",
    title: "Beachfront Luxury Home",
    description: "Exclusive beachfront property with direct access to the ocean and stunning views.",
    location: "Banana Island, Lagos",
    price: 850000,
    priceType: "monthly",
    bedrooms: 6,
    bathrooms: 7,
    squareFeet: 6000,
    images: ["/lagos-beachfront-luxury-home.png"],
    featured: true,
    propertyType: "house",
    amenities: ["Private Beach", "Swimming Pool", "Garden", "Security"],
    rating: 4.9,
    reviews: 45,
    dates: "Available all year",
    favorite: false,
    type: "House",
    beds: 6,
    baths: 5,
    maxGuests: 12,
    categories: ["beachfront", "luxury"],
    yearBuilt: 2022,
    newListing: true,
  },
  {
    id: "6",
    title: "Serviced Apartment in Ikeja",
    description: "Fully serviced apartment with modern amenities and convenient location.",
    location: "Ikeja GRA, Lagos",
    price: 150000,
    priceType: "monthly",
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1100,
    images: ["/ikeja-serviced-apartment.png"],
    featured: false,
    propertyType: "apartment",
    amenities: ["Cleaning Service", "24/7 Security", "Parking", "Internet"],
    rating: 4.6,
    reviews: 112,
    dates: "Available all year",
    favorite: false,
    type: "Apartment",
    beds: 2,
    baths: 2,
    maxGuests: 4,
    categories: ["apartments", "shortlets"],
    yearBuilt: 2017,
  },
  {
    id: "7",
    title: "Penthouse with City Views",
    description: "Luxurious penthouse offering panoramic views of the Lagos skyline.",
    location: "Victoria Island, Lagos",
    price: 350000,
    priceType: "monthly",
    bedrooms: 4,
    bathrooms: 4,
    squareFeet: 3200,
    images: ["/lagos-penthouse-view.png"],
    featured: true,
    propertyType: "penthouse",
    amenities: ["Rooftop Terrace", "Swimming Pool", "Gym", "Security"],
    rating: 4.7,
    reviews: 34,
    dates: "Available all year",
    favorite: false,
    type: "Penthouse",
    beds: 4,
    baths: 3,
    maxGuests: 8,
    categories: ["penthouses", "luxury"],
    yearBuilt: 2020,
  },
  {
    id: "8",
    title: "Cozy Studio in Yaba",
    description: "Comfortable studio apartment perfect for young professionals or students.",
    location: "Yaba, Lagos",
    price: 80000,
    priceType: "monthly",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 500,
    images: ["/cozy-yaba-studio.png"],
    featured: false,
    propertyType: "studio",
    amenities: ["Security", "Parking", "Internet"],
    rating: 4.5,
    reviews: 78,
    dates: "Available all year",
    favorite: false,
    type: "Studio",
    beds: 1,
    baths: 1,
    maxGuests: 2,
    categories: ["apartments", "shortlets"],
    yearBuilt: 2018,
  },
  {
    id: "9",
    title: "Farmhouse with Acreage",
    description: "Spacious farmhouse on 5 acres of land, perfect for agriculture or retreat.",
    location: "Epe, Lagos",
    price: 25000000,
    priceType: "sale",
    landSize: 5,
    landUnit: "acres",
    images: ["/nigerian-farmhouse.png"],
    featured: false,
    propertyType: "farm",
    isLandedProperty: true,
    amenities: ["Water Supply", "Electricity", "Road Access"],
    rating: 4.8,
    reviews: 28,
    dates: "Available all year",
    favorite: false,
    type: "House",
    beds: 4,
    baths: 3,
    maxGuests: 8,
    categories: ["countryside"],
    yearBuilt: 2015,
  },
  {
    id: "10",
    title: "Modern Office Space",
    description: "Contemporary office space in a prime business district.",
    location: "Victoria Island, Lagos",
    price: 400000,
    priceType: "monthly",
    squareFeet: 2000,
    images: ["/modern-lagos-office.png"],
    featured: false,
    propertyType: "office",
    amenities: ["High-Speed Internet", "Parking", "Security"],
    rating: 4.7,
    reviews: 34,
    dates: "Available all year",
    favorite: false,
    type: "Commercial",
    beds: 0,
    baths: 2,
    maxGuests: 0,
    categories: ["commercial"],
    yearBuilt: 2020,
  },
]
