export const categories = [
  {
    id: "all",
    name: "All Properties",
    description: "Browse our complete collection of premium properties across Nigeria.",
    image: "/diverse-property-showcase.png",
    count: 500,
    featured: false,
  },
  {
    id: "apartments",
    name: "Luxury Apartments",
    description: "Discover elegant apartments with premium amenities and stunning views.",
    image: "/luxury-ocean-view-apartment.png",
    count: 120,
    featured: true,
  },
  {
    id: "villas",
    name: "Beachfront Villas",
    description: "Experience the ultimate luxury with our exclusive beachfront villas.",
    image: "/elegant-villa-lagos.png",
    count: 45,
    featured: true,
  },
  {
    id: "penthouses",
    name: "City Penthouses",
    description: "Enjoy breathtaking city views from our premium penthouse collection.",
    image: "/lagos-penthouse-view.png",
    count: 38,
    featured: false,
  },
  {
    id: "shortlets",
    name: "Serviced Apartments",
    description: "Perfect for short stays with all the comforts of home and hotel amenities.",
    image: "/ikeja-serviced-apartment.png",
    count: 95,
    featured: false,
  },
  {
    id: "beachfront",
    name: "Beachfront Properties",
    description: "Wake up to stunning ocean views and direct beach access.",
    image: "/lagos-beachfront-luxury-home.png",
    count: 32,
    featured: false,
  },
  {
    id: "commercial",
    name: "Commercial Spaces",
    description: "Premium office spaces and retail locations for your business.",
    image: "/modern-lagos-office.png",
    count: 67,
    featured: false,
  },
  {
    id: "countryside",
    name: "Countryside Retreats",
    description: "Escape the city with our peaceful countryside properties.",
    image: "/nigerian-farmhouse.png",
    count: 28,
    featured: false,
  },
]
