-- Insert sample properties into the database
-- First, let's create a sample admin user profile (you'll need to sign up first)

-- Insert sample properties (replace owner_id with actual user IDs from your auth.users table)
INSERT INTO public.properties (
    title, description, location, address, city, state, price, category, property_type,
    bedrooms, bathrooms, square_feet, max_guests, images, amenities, features,
    rating, review_count, featured, available, verified, status, owner_id
) VALUES 
-- BUY PROPERTIES
(
    'Luxury Ocean View Apartment',
    'Stunning 3-bedroom apartment with panoramic ocean views in the heart of Victoria Island. This exquisite property features floor-to-ceiling windows, premium finishes, and access to world-class amenities including a rooftop infinity pool and private beach access.',
    'Victoria Island, Lagos',
    '123 Ahmadu Bello Way',
    'Lagos',
    'Lagos',
    150000000,
    'buy',
    'Apartment',
    3,
    3,
    2500,
    6,
    ARRAY['/luxury-ocean-view-apartment.png', '/modern-ikoyi-apartment.png', '/elegant-villa-lagos.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Swimming Pool', 'Gym', 'Parking', 'Security', 'Ocean View', 'Concierge', 'Elevator'],
    ARRAY['Ocean View', 'Modern Kitchen', 'Balcony', 'Elevator Access', 'Smart Home', 'Premium Finishes'],
    4.9,
    127,
    true,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Executive Penthouse Ikoyi',
    'Ultra-luxury penthouse spanning two floors with private elevator access. Features include a private rooftop terrace, wine cellar, home theater, and panoramic city views. Perfect for discerning buyers seeking the pinnacle of luxury living.',
    'Ikoyi, Lagos',
    '456 Kingsway Road',
    'Lagos',
    'Lagos',
    450000000,
    'buy',
    'Penthouse',
    5,
    6,
    5500,
    10,
    ARRAY['/lagos-penthouse-view.png', '/luxury-ocean-view-apartment.png', '/modern-ikoyi-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Private Pool', 'Gym', 'Parking', 'Security', 'Wine Cellar', 'Home Theater', 'Rooftop Terrace', 'Private Elevator'],
    ARRAY['City Views', 'Wine Cellar', 'Home Theater', 'Rooftop Terrace', 'Private Elevator', 'Smart Home', 'Premium Appliances'],
    4.95,
    89,
    true,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Elegant Villa Lagos',
    'Spacious 4-bedroom villa with private garden and swimming pool in exclusive Ikoyi neighborhood. This architectural masterpiece combines modern design with traditional elegance, featuring high ceilings, marble floors, and lush landscaping.',
    'Ikoyi, Lagos',
    '789 Alexander Avenue',
    'Lagos',
    'Lagos',
    280000000,
    'buy',
    'Villa',
    4,
    4,
    3500,
    8,
    ARRAY['/elegant-villa-lagos.png', '/lagos-beachfront-luxury-home.png', '/modern-ikoyi-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Swimming Pool', 'Garden', 'Parking', 'Security', 'Generator', 'Staff Quarters', 'Study Room'],
    ARRAY['Private Pool', 'Garden', 'Modern Kitchen', 'Study Room', 'Garage', 'Staff Quarters', 'High Ceilings'],
    4.8,
    156,
    true,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Modern Banana Island Mansion',
    'Spectacular waterfront mansion on prestigious Banana Island. This 6-bedroom estate features private beach access, boat dock, infinity pool, and state-of-the-art smart home technology. The epitome of luxury island living.',
    'Banana Island, Lagos',
    '101 Banana Island Road',
    'Lagos',
    'Lagos',
    850000000,
    'buy',
    'Mansion',
    6,
    7,
    8000,
    12,
    ARRAY['/lagos-beachfront-luxury-home.png', '/elegant-villa-lagos.png', '/luxury-ocean-view-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Private Beach', 'Swimming Pool', 'Boat Dock', 'Gym', 'Parking', 'Security', 'Generator', 'Staff Quarters', 'Wine Cellar'],
    ARRAY['Private Beach', 'Boat Dock', 'Infinity Pool', 'Wine Cellar', 'Home Theater', 'Smart Home', 'Guest House'],
    4.98,
    67,
    true,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Contemporary Lekki Duplex',
    'Brand new 4-bedroom duplex in a gated estate in Lekki Phase 1. Features modern architecture, smart home integration, solar power system, and access to estate amenities including clubhouse and recreational facilities.',
    'Lekki Phase 1, Lagos',
    '202 Admiralty Way',
    'Lagos',
    'Lagos',
    95000000,
    'buy',
    'Duplex',
    4,
    4,
    3200,
    8,
    ARRAY['/lekki-apartment.png', '/modern-ikoyi-apartment.png', '/elegant-villa-lagos.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Swimming Pool', 'Gym', 'Parking', 'Security', 'Generator', 'Solar Power', 'Clubhouse'],
    ARRAY['Solar Power', 'Smart Home', 'Gated Estate', 'Clubhouse Access', 'Modern Kitchen', 'En-suite Bedrooms'],
    4.7,
    94,
    false,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),

-- RENT PROPERTIES
(
    'Modern Lekki Apartment',
    'Contemporary 2-bedroom apartment in the prestigious Lekki Phase 1 area. Fully furnished with modern appliances, high-speed internet, and access to estate facilities including swimming pool and gym.',
    'Lekki Phase 1, Lagos',
    '303 Chevron Drive',
    'Lagos',
    'Lagos',
    2500000,
    'rent',
    'Apartment',
    2,
    2,
    1800,
    4,
    ARRAY['/lekki-apartment.png', '/modern-ikoyi-apartment.png', '/luxury-ocean-view-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Parking', 'Security', 'Generator', 'Swimming Pool', 'Gym', 'Furnished'],
    ARRAY['Modern Design', 'Fitted Kitchen', 'Balcony', 'Furnished', 'High-Speed Internet'],
    4.7,
    89,
    false,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Luxury Serviced Apartment VI',
    'Premium 3-bedroom serviced apartment in Victoria Island with daily housekeeping, concierge services, and access to 5-star hotel amenities. Perfect for executives and expatriates.',
    'Victoria Island, Lagos',
    '404 Tiamiyu Savage Street',
    'Lagos',
    'Lagos',
    4500000,
    'rent',
    'Serviced Apartment',
    3,
    3,
    2200,
    6,
    ARRAY['/luxury-ocean-view-apartment.png', '/modern-ikoyi-apartment.png', '/lagos-penthouse-view.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Gym', 'Parking', 'Security', 'Elevator', 'Concierge', 'Housekeeping', 'Room Service'],
    ARRAY['Ocean View', 'Concierge Service', 'Daily Housekeeping', 'Premium Furnishing', 'Business Center'],
    4.85,
    142,
    true,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Family House Magodo',
    'Spacious 4-bedroom detached house in the serene Magodo GRA. Features include a large compound, boys quarters, generator house, and ample parking space. Ideal for families seeking comfort and security.',
    'Magodo GRA, Lagos',
    '505 CMD Road',
    'Lagos',
    'Lagos',
    3200000,
    'rent',
    'Detached House',
    4,
    4,
    3000,
    8,
    ARRAY['/elegant-villa-lagos.png', '/nigerian-farmhouse.png', '/modern-ikoyi-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Parking', 'Security', 'Generator', 'Garden', 'Boys Quarters', 'CCTV'],
    ARRAY['Large Compound', 'Boys Quarters', 'Generator House', 'Family Friendly', 'Quiet Neighborhood'],
    4.6,
    78,
    false,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Executive Flat Ikeja GRA',
    'Well-appointed 3-bedroom flat in the prestigious Ikeja GRA. Close to the airport and business districts, this property offers convenience and comfort with modern amenities and 24/7 security.',
    'Ikeja GRA, Lagos',
    '606 Obafemi Awolowo Way',
    'Lagos',
    'Lagos',
    2800000,
    'rent',
    'Flat',
    3,
    3,
    2000,
    6,
    ARRAY['/ikeja-serviced-apartment.png', '/modern-ikoyi-apartment.png', '/lekki-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Parking', 'Security', 'Generator', 'Elevator', 'CCTV', 'Intercom'],
    ARRAY['Airport Proximity', 'Business District', '24/7 Security', 'Elevator Access', 'Modern Fittings'],
    4.5,
    65,
    false,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Luxury Duplex Lekki Phase 2',
    'Exquisite 5-bedroom duplex in an exclusive Lekki Phase 2 estate. Features include a private swimming pool, landscaped garden, smart home automation, and premium security systems.',
    'Lekki Phase 2, Lagos',
    '707 Mobil Road',
    'Lagos',
    'Lagos',
    6500000,
    'rent',
    'Duplex',
    5,
    5,
    4000,
    10,
    ARRAY['/elegant-villa-lagos.png', '/lagos-beachfront-luxury-home.png', '/luxury-ocean-view-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Private Pool', 'Garden', 'Parking', 'Security', 'Generator', 'Smart Home', 'CCTV'],
    ARRAY['Private Pool', 'Smart Home', 'Landscaped Garden', 'Premium Security', 'Exclusive Estate'],
    4.9,
    112,
    true,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),

-- SHORTLET PROPERTIES
(
    'Cozy Yaba Studio',
    'Perfect studio apartment for short stays in the vibrant Yaba district. Ideal for business travelers and young professionals, featuring modern amenities and excellent connectivity to major business areas.',
    'Yaba, Lagos',
    '808 Herbert Macaulay Way',
    'Lagos',
    'Lagos',
    25000,
    'shortlet',
    'Studio',
    1,
    1,
    600,
    2,
    ARRAY['/cozy-yaba-studio.png', '/modern-ikoyi-apartment.png', '/lekki-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Kitchen', 'Parking', 'Security', 'Work Desk', 'Smart TV'],
    ARRAY['Compact Design', 'Kitchenette', 'Work Space', 'Business District', 'Public Transport'],
    4.5,
    43,
    false,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
),
(
    'Lagos Beachfront Luxury Home',
    'Exclusive beachfront property with private beach access and stunning sunset views. Perfect for luxury getaways, family vacations, and special celebrations with world-class amenities and personalized service.',
    'Lekki, Lagos',
    '909 Lekki-Epe Expressway',
    'Lagos',
    'Lagos',
    45000,
    'shortlet',
    'Villa',
    5,
    5,
    4500,
    10,
    ARRAY['/lagos-beachfront-luxury-home.png', '/elegant-villa-lagos.png', '/luxury-ocean-view-apartment.png'],
    ARRAY['WiFi', 'Air Conditioning', 'Private Beach', 'Swimming Pool', 'BBQ Area', 'Parking', 'Security', 'Chef Service', 'Boat Access'],
    ARRAY['Beach Access', 'Sunset Views', 'Private Pool', 'Entertainment Area', 'Chef Kitchen', 'Boat Dock'],
    4.9,
    203,
    true,
    true,
    true,
    'active',
    (SELECT id FROM auth.users LIMIT 1)
);

-- Update property counts and ratings
UPDATE public.properties SET view_count = FLOOR(RANDOM() * 1000) + 100;
UPDATE public.properties SET favorite_count = FLOOR(RANDOM() * 50) + 5;
